package net.derpaul.utility.m3ugen;

/*
 * GUIMain.java
 *
 * Created on 13. März 2003, 16:45
 */
import javax.swing.JFileChooser;
import java.awt.Cursor;
import java.awt.HeadlessException;

/**
 *
 * @author paul
 */
public class GUIMain extends javax.swing.JFrame {

    /**
     *
     */
    private final static String strLabelButtonMP3Dir = "MP3-Dir";

    /**
     * Extension of mp3 files
     */
    public final static String strExtensionMP3 = ".mp3";

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        objJLabelInfo = new javax.swing.JLabel();
        objJPanelMain = new javax.swing.JPanel();
        objJPanelTop = new javax.swing.JPanel();
        objJTextFieldBaseDir = new javax.swing.JTextField();
        objJButtonDirectory = new javax.swing.JButton();
        objJPanelBottom = new javax.swing.JPanel();
        objJPanelButtons = new javax.swing.JPanel();
        objJButtonStart = new javax.swing.JButton();
        objJButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M3UGen");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        objJLabelInfo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        objJLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        objJLabelInfo.setText("M3UGen (C) 2003 Jochen Paul");
        objJLabelInfo.setToolTipText("M3UGen (C) 2003 Jochen Paul");
        getContentPane().add(objJLabelInfo, java.awt.BorderLayout.SOUTH);

        objJPanelMain.setLayout(new java.awt.GridLayout(2, 1, 2, 2));

        objJPanelTop.setLayout(new java.awt.BorderLayout(2, 2));

        objJTextFieldBaseDir.setText("Base path");
        objJTextFieldBaseDir.setToolTipText("Base path");
        objJTextFieldBaseDir.setMaximumSize(new java.awt.Dimension(200, 20));
        objJTextFieldBaseDir.setMinimumSize(new java.awt.Dimension(200, 20));
        objJTextFieldBaseDir.setPreferredSize(new java.awt.Dimension(200, 20));
        objJPanelTop.add(objJTextFieldBaseDir, java.awt.BorderLayout.CENTER);

        objJButtonDirectory.setText("Dir");
        objJButtonDirectory.setToolTipText("Dir");
        objJButtonDirectory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                objJButtonDirectoryMouseReleased(evt);
            }
        });
        objJPanelTop.add(objJButtonDirectory, java.awt.BorderLayout.EAST);

        objJPanelMain.add(objJPanelTop);

        objJPanelBottom.setLayout(new java.awt.BorderLayout(2, 2));

        objJPanelButtons.setLayout(new java.awt.GridLayout(1, 2, 2, 2));

        objJButtonStart.setText("Start");
        objJButtonStart.setToolTipText("Start");
        objJButtonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                objJButtonStartMouseReleased(evt);
            }
        });
        objJPanelButtons.add(objJButtonStart);

        objJButtonExit.setText("Exit");
        objJButtonExit.setToolTipText("Exit");
        objJButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                objJButtonExitMouseReleased(evt);
            }
        });
        objJPanelButtons.add(objJButtonExit);

        objJPanelBottom.add(objJPanelButtons, java.awt.BorderLayout.CENTER);

        objJPanelMain.add(objJPanelBottom);

        getContentPane().add(objJPanelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void objJButtonDirectoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_objJButtonDirectoryMouseReleased
        // Add your handling code here:
        final JFileChooser objJFileChooser = new JFileChooser();
        int returnVal;

        try {
            objJFileChooser.setDialogTitle("Select path containing MP3s");
            objJFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            objJFileChooser.setMultiSelectionEnabled(false);
            returnVal = objJFileChooser.showDialog(this, GUIMain.strLabelButtonMP3Dir);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                this.objJTextFieldBaseDir.setText(objJFileChooser.getSelectedFile().getAbsolutePath());
            }
        } catch (HeadlessException e) {
        }
    }//GEN-LAST:event_objJButtonDirectoryMouseReleased

    private void objJButtonExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_objJButtonExitMouseReleased
        // Add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_objJButtonExitMouseReleased

    private void objJButtonStartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_objJButtonStartMouseReleased
        SearchEngine plWork;
        String tmpVal;

        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            plWork = new SearchEngine(this.objJTextFieldBaseDir.getText());
            tmpVal = plWork.startSearch();
            this.objJLabelInfo.setText(tmpVal);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_objJButtonStartMouseReleased

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GUIMain objGUIMain = new GUIMain();

        objGUIMain.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton objJButtonDirectory;
    private javax.swing.JButton objJButtonExit;
    private javax.swing.JButton objJButtonStart;
    private javax.swing.JLabel objJLabelInfo;
    private javax.swing.JPanel objJPanelBottom;
    private javax.swing.JPanel objJPanelButtons;
    private javax.swing.JPanel objJPanelMain;
    private javax.swing.JPanel objJPanelTop;
    private javax.swing.JTextField objJTextFieldBaseDir;
    // End of variables declaration//GEN-END:variables

}
